title: Your awesome title
author: breton16
email: breton16@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A wild GH page that references the New York Yankees a few times!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  breton16 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
